version: '2.1'
services:
  mariadb-backup:
    build: ./mariadb
    env_file:
      - mariadb/.env
    volumes:
      - ${BASE_DATA_DIR:-/srv}/mariadb/backups:/srv/mysql-bak
      - ${BASE_DATA_DIR:-/srv}/mariadb/datadir:/var/lib/mysql
      - ${BASE_DATA_DIR:-/srv}/mariadb/conf:/etc/mysql/conf.d
    links:
      - mariadb
    labels:
      cron.schedule: ${BACKUP_SCHEDULE:-@every 6h}

  container-crontab:
    image: rancher/container-crontab:v0.2.0
    restart: always
    container_name: crontab
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
