version: '2.1'
services:
  php-fpm:
    build: ./php-fpm
    restart: always
    volumes:
      - ${BASE_DATA_DIR:-/srv}/pwk:/srv/caddy/html
    links:
      - mariadb

  mariadb:
    image: mariadb:10
    restart: always
    env_file:
      - mariadb/.env
    volumes:
      - ${BASE_DATA_DIR:-/srv}/mariadb/datadir:/var/lib/mysql
      - ${BASE_DATA_DIR:-/srv}/mariadb/conf:/etc/mysql/conf.d

  caddy:
    build: ./caddy
    restart: always
    env_file:
      - caddy/.env
    ports:
      - 80:80
      - 443:443
    volumes:
      - ${BASE_DATA_DIR:-/srv}/pwk:/srv/caddy/html
      - ${BASE_DATA_DIR:-/srv}/caddy/config:/srv/caddy/.caddy
    links:
      - php-fpm
