version: '3.7'
services:
  php-fpm:
    build: ./php-fpm
    labels:
      autoheal: "true"
    restart: always
    volumes:
      - ${BASE_DATA_DIR:-/srv}/mtm:/srv/caddy/html

  mysql:
    image: mysql:5.7
    labels:
      autoheal: "true"
    restart: always
    env_file:
      - mysql/.env
    volumes:
      - ${BASE_DATA_DIR:-/srv}/mysql/datadir:/var/lib/mysql
      - ${BASE_DATA_DIR:-/srv}/mysql/conf:/etc/mysql/conf.d
    healthcheck:
      test: mysql --user=$$MYSQL_USER --password=$$MYSQL_PASSWORD --database=$$MYSQL_DATABASE -e "SELECT 1" >/dev/null || exit 1
      interval: 30s
      timeout: 3s
      retries: 2

  caddy:
    build: ./caddy
    labels:
      autoheal: "true"
    restart: always
    env_file:
      - caddy/.env
    volumes:
      - ${BASE_DATA_DIR:-/srv}/mtm:/srv/caddy/html
      - ${BASE_DATA_DIR:-/srv}/caddy/config:/srv/caddy/.caddy

  autoheal:
    image: willfarrell/autoheal
    restart: always
    container_name: autoheal
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
